services:
  # 1. Database Service (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: nodejs-capstone-project
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs-capstone

    ports:
      - "5440:5432"

volumes:
  postgres_data: